# NOTA: Mapeo de aplicaciones a iconos (Nerd Fonts) para Sway
# INFO: Sworkstyle renombra los espacios de trabajo dinÃ¡micamente

# Separador entre iconos si hay varias apps en el mismo workspace
separator = ' '

[matching]

# -------------------------
# Terminales y Editores
# -------------------------
# Detectar Neovim por tÃ­tulo (nvim + nombre de archivo opcional)
'/nvim.*/' = 'ï¯'
'/vim.*/' = 'îŸ…'
# Detectar Yazi (Gestor de archivos)
'/Yazi.*/' = 'ï¼'
# Detectar Lazygit
'/lazygit/' = 'ï‡“'
# Terminales genÃ©ricas
'kitty' = 'ï„ '
'cool-retro-term.cool-retro-term' = 'ï„ '
'Alacritty' = 'ï„ '

# -------------------------
# Navegadores y Web
# -------------------------
'firefox' = 'ó°ˆ¹'
'firefox-developer-edition' = 'ó°ˆ¹'
'Google-chrome' = 'ï‰¨'
'Chromium-browser' = 'ï‰¨'
'Brave-browser' = 'ğŸ¦'
'/Private Browsing/' = 'ó±€£'
'/Picture-in-Picture/' = 'ó°¹—'

# -------------------------
# Desarrollo y Herramientas
# -------------------------
'jetbrains-idea-ce' = 'îµ'
'jetbrains-idea' = 'îµ'
'code-oss' = 'ó°¨'
'Code' = 'ó°¨'
'deno' = 'î¬¨'
'Postman' = 'î·…'
'org.keepassxc.KeePassXC' = 'ó±•´'

# -------------------------
# ComunicaciÃ³n y Social
# -------------------------
'org.telegram.desktop' = 'ï‹†'
'Skype' = 'ó°’¯'
'/Element/' = 'ó°¯¸'
'vesktop' = 'ï‡¿'
'discord' = 'ï‡¿'

# -------------------------
# Multimedia y GrÃ¡ficos
# -------------------------
'mpv' = 'ï®'
'imv' = 'ï€¾'
'vlc' = 'ó°•¼'
'spotube' = 'ï†¼'
'spotify' = 'ï†¼'
'obs' = 'ó°‘‹'
'com.obsproject.Studio' = 'ó°‘‹'
'krita' = 'ïŒ½'
'gimp' = 'ïŒ¸'
'inkscape' = 'ïŒ»'
'blender' = 'ó°‚«'
'com.github.wwmm.easyeffects' = 'ó°¥ '

# -------------------------
# Sistema y Archivos
# -------------------------
# Gestores de archivos grÃ¡ficos
'org.gnome.Nautilus' = 'ï¼'
'thunar' = 'ï¼'
'pcmanfm' = 'ï¼'
# Monitores de sistema
'/btop/' = 'î®¢'
'/htop/' = 'î®¢'
'/nmtui/' = 'ï‡«'
'/pulsemixer/' = 'ï‡'
'pavucontrol' = 'ï‡'

# -------------------------
# Oficina y Productividad
# -------------------------
'obsidian' = 'îŠŒ'
'org.pwmt.zathura' = 'ï‡'
'evince' = 'ï‡'
'libreoffice-startcenter' = 'ó°¹¯'
'libreoffice-writer' = 'ï‡‚'
'libreoffice-calc' = 'ï‡ƒ'
'libreoffice-impress' = 'ï‡„'
'libreoffice-draw' = 'ï‡¼'
'libreoffice-base' = 'ï‡€'
'soffice' = 'ï‡€'

# -------------------------
# Juegos
# -------------------------
'steam' = 'ï†¶'
'lutris' = 'ó°“‡'
'heroic' = 'ó°ºµ'
'minecraft' = 'ó°³'
